# This is a basic workflow to help you get started with Actions

name: pushfix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the history branch
on:
  repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install dependecies
      run: |
        sudo apt-get -y install tidy cleancss
        sudo npm install -g csso-cli
        sudo npm install -g css-purge
        sudo npm install -g rename-css-selectors

    # Runs a set of commands using the runners shell
    - name: Forced push keep history
      run: |
        git config user.email "gitcommits@dewmill.com"
        git config user.name "Fixpush bot"
        mkdir ../keep
        [ '.[!.]*' = "$(echo .[!.]*)" ] || mv .[!.]* ../keep/
        [ '..?*' = "$(echo ..?*)" ] || mv ..?* ../keep/
        mv ../keep/.git .
        git fetch origin master
        git checkout origin/master -- .
        tidy -omit -ashtml -i -q --wrap 0 -m index.html || [[ $? -eq 1 ]]
        
        NODE_PATH=$(npm root -g) node -e 'const rcs = require("rename-css-selectors");
          try { rcs.process.autoSync(["index.html"], options);
          rcs.generateMappingSync("./", { overwrite: true });
          } catch (err) {
            console.error(err);
          }'
        
        perl -0777 -ne 'while(m#<style[^>]*>([^<]*)</style>\n?#g){print "$1\n";}' index.html > index.css
        perl -0777 -pe 's#<style[^>]*>([^<]*)</style>\n?##g' index.html > index_new.html
        css-purge -i index.css -m index_new.html -o index.css2
        csso --force-media-merge -i index.css2 -o index.css3
        cleancss -O2 --format beautify index.css3 > index.css4        
  
        perl -0777 -pe 's#</head>#<link rel="stylesheet" type="text/css" href="index.css" /></head>#g' index.html > index_new.html
        mv index_new.html index.html
        mv index.css4 index.css  
        rm index.css2 index.css3 index_new.html
        
        [ '../keep/.[!.]*' = "$(echo ../keep/.[!.]*)" ] || mv ../keep/.[!.]* .
        [ '../keep/..?*' = "$(echo ../keep/..?*)" ] || mv ../keep/..?* .
        git add -A
        git commit -m "Changes $(date --rfc-2822)"
        git push
