# This is a basic workflow to help you get started with Actions

name: pushfix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the history branch
on:
  repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install dependecies
      run: |
        sudo apt-get -q -y install tidy csstidy
        sudo npm install -g csso-cli
        sudo npm install -g css-purge
        sudo npm install -g rename-css-selectors
        sudo npm install -g clean-css-cli

    # Runs a set of commands using the runners shell
    - name: Forced push keep history
      run: |
        git config user.email "gitcommits@dewmill.com"
        git config user.name "Fixpush bot"
        mkdir ../keep
        [ '.[!.]*' = "$(echo .[!.]*)" ] || mv .[!.]* ../keep/
        [ '..?*' = "$(echo ..?*)" ] || mv ..?* ../keep/
        mv ../keep/.git .
        
        echo "Copy latest files"
        git fetch origin master
        rm -rf *
        git checkout origin/master -- .
        
        [ '../keep/.[!.]*' = "$(echo ../keep/.[!.]*)" ] || mv ../keep/.[!.]* .
        [ '../keep/..?*' = "$(echo ../keep/..?*)" ] || mv ../keep/..?* .
        
        for FILE in *.html; do
        
          echo "Size of $FILE: $(stat -c%s $FILE)"
          if [ "$(stat -c%s $FILE)" -eq "0" ]; then
            continue
          fi
        
          echo "Run tidy on $FILE"
          #tidy --show-warnings no -omit -ashtml -i 2 -q --wrap 0 -m "$FILE" || [[ $? -eq 1 ]]
          tidy -i 2 --quiet yes --show-body-only auto --show-errors 0 --wrap 0 -m "$FILE" || [[ $? -eq 1 ]]
        
          echo "Extract css from html for $FILE"
          perl -0777 -ne 'while(m#<style[^>]*>([^<]*)</style>\n?#g){print "$1\n";}' "$FILE" > "$FILE.css"
          perl -0777 -pe 's#<style[^>]*>([^<]*)</style>\n?##g' "$FILE" > "$FILE.2" && mv "$FILE.2" "$FILE"
        
          #echo "Run csdtidy"
          #csstidy index.css index.css.2 && mv index.css.2 index.css


          echo "Run csso on $FILE"
          #csso --force-media-merge -i "$FILE.css" -o "$FILE.css.2" && mv "$FILE.css.2" "$FILE.css"
          csso -i "$FILE.css" -o "$FILE.css.2" && mv "$FILE.css.2" "$FILE.css"
        
          echo "Run cleancss on $FILE"
          cleancss -O2 --format beautify "$FILE.css" > "$FILE.css.2" && mv "$FILE.css.2" "$FILE.css"
        
        
          #echo "Run css-purge on $FILE"
          #css-purge -i "$FILE.css" -m "$FILE" -o "$FILE.css.2" && mv "$FILE.css.2" "$FILE.css"
        
          echo "Re-insert css link in html in $FILE"
          perl -0777 -pe 's#<body#<link rel="stylesheet" type="text/css" href="'$FILE.css'" /><body#g' "$FILE" > "$FILE.2" && mv "$FILE.2" "$FILE"
    
          #echo "Run rename-css-selectors"
          #NODE_PATH=$(npm root -g) node -e 'const rcs = require("rename-css-selectors");
          #  try { rcs.process.autoSync(["index.html", "**/*.css"]);
          #  rcs.generateMappingSync("./", { overwrite: true,  });
          #  } catch (err) {
          #    console.error(err);
          #  }' && mv rcs/* . && rmdir rcs && rm -f renaming_map.json
        done
        
        echo "Create and push commit"
        git add -A
        git status
        git commit -m "Changes $(date --rfc-2822)"
        git push
