# This is a basic workflow to help you get started with Actions

name: pushfix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the history branch
on:
  repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install dependecies
      run: |
        sudo apt-get install tidy

    # Runs a set of commands using the runners shell
    - name: Forced push keep history
      run: |
        git config user.email "gitcommits@dewmill.com"
        git config user.name "Fixpush bot"
        mkdir ../keep
        [ '.[!.]*' = "$(echo .[!.]*)" ] || mv .[!.]* ../keep/
        [ '..?*' = "$(echo ..?*)" ] || mv ..?* ../keep/
        mv ../keep/.git .
        git fetch origin master
        git checkout origin/master -- .
        (tidy -q -m index.html; if [ "$?" = "0" -o "$?" = "1" ]; then return 0; else return 1; fi)
        [ '../keep/.[!.]*' = "$(echo ../keep/.[!.]*)" ] || mv ../keep/.[!.]* .
        [ '../keep/..?*' = "$(echo ../keep/..?*)" ] || mv ../keep/..?* .
        git add -A
        git commit -m "Changes $(date --rfc-2822)"
        git push
